require 'formula'

class Libplist < Formula
  homepage 'http://cgit.sukimashita.com/libplist.git/'
  url 'http://cgit.sukimashita.com/libplist.git/snapshot/libplist-1.10.tar.bz2'
  sha1 'a642bb37eaa4bec428d0b2a4fa8399d80ee73a18'

  head 'http://git.sukimashita.com/libplist.git'

  # Improve the default option descr. generated by `depends_on :python => :optional`
  option 'with-python', 'Enable Cython Python bindings'

  depends_on 'cmake' => :build
  depends_on :python => :optional
  depends_on 'Cython' => :python if build.with? 'python'

  def patches
    DATA
  end

  def install
    ENV.deparallelize # make fails on an 8-core Mac Pro
    ENV.universal_binary
    args = std_cmake_args

    # Disable Swig Python bindings
    args << "-DENABLE_SWIG='OFF'"

    if python do
      # For Xcode-only systems, the headers of system's python are inside of Xcode:
      args << "-DPYTHON_INCLUDE_DIR='#{python.incdir}'"
      # Cmake picks up the system's python dylib, even if we have a brewed one:
      args << "-DPYTHON_LIBRARY='#{python.libdir}/lib#{python.xy}.dylib'"
    end; else
      # Also disable Cython Python bindings if we're not building --with-python
      args << "-DENABLE_CYTHON='OFF'"
    end
    system "cmake", ".", "-DCMAKE_INSTALL_NAME_DIR=#{lib}", *args
    system "make install"
  end

  def caveats
    python.standard_caveats if python
  end
end

__END__
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index c4f5483..e30d7cc 100644
--- a/src/CMakeLists.txt  
+++ b/src/CMakeLists.txt
@@ -45,6 +45,16 @@ if(APPLE)
   SET_TARGET_PROPERTIES( plist PROPERTIES INSTALL_NAME_DIR "${CMAKE_INSTALL_PREFIX}/lib")
 endif()
 
+SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DPLIST_BYTE_ORDER=${PLIST_BYTE_ORDER}")
+ADD_LIBRARY( pliststatic STATIC ${libplist_SRC} ${libcnary_object_files} )
+TARGET_LINK_LIBRARIES( pliststatic ${LIBXML2_LIBRARIES} )
+SET_TARGET_PROPERTIES( pliststatic PROPERTIES VERSION ${LIBPLIST_LIBVERSION} )
+SET_TARGET_PROPERTIES( pliststatic PROPERTIES SOVERSION ${LIBPLIST_SOVERSION} )
+SET_TARGET_PROPERTIES(pliststatic PROPERTIES OUTPUT_NAME plist)
+if(APPLE)
+  SET_TARGET_PROPERTIES( pliststatic PROPERTIES INSTALL_NAME_DIR "${CMAKE_INSTALL_PREFIX}/lib")
+endif()
+
 ADD_LIBRARY( plist++ SHARED ${libplist++_SRC} )
 TARGET_LINK_LIBRARIES( plist++ plist )
 SET_TARGET_PROPERTIES( plist++ PROPERTIES VERSION ${LIBPLIST_LIBVERSION} )
@@ -53,7 +63,7 @@ if(APPLE)
   SET_TARGET_PROPERTIES( plist++ PROPERTIES INSTALL_NAME_DIR "${CMAKE_INSTALL_PREFIX}/lib")
 endif()
 
-INSTALL(TARGETS plist plist++
+INSTALL(TARGETS plist plist++ pliststatic
  RUNTIME DESTINATION bin COMPONENT lib
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT dev
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT dev)
